<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ks</string>
	</array>
	<key>name</key>
	<string>o2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\[)(o2_iscript)(\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.o2</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\[)(o2_endscript)(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.o2</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
			</dict>
			<key>name</key>
			<string>embedded-js.o2</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[)([a-zA-Z0-9_\p{Han}\p{Hiragana}\p{Katakana}\p{S}ー・\(\)（）]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.o2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
			</dict>
			<key>name</key>
			<string>tag.o2</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.o2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.o2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.o2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.o2</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.singlequotes.o2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.o2</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w &amp;&gt;&lt;;!?\.,\"_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.o2</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(\")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.o2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.o2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.o2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.o2</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.doublequotes.o2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.o2</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w &amp;&gt;&lt;;!?\.,\'_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.o2</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.o2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.o2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.o2</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w]*)\s*([=])\s*|([\w&amp;:\(\)\.,\-0-9_a-zA-Z\p{Han}\p{Hiragana}\p{Katakana}\p{S}]+)</string>
					<key>name</key>
					<string>tag.noquotes.o2</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[ 	]{0,}+@([a-zA-Z0-9_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.o2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
			</dict>
			<key>name</key>
			<string>tag.o2</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.o2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.o2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.o2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.o2</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.singlequotes.o2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.o2</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w ?\.,\"_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.o2</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>([\w]+)\s*(=)\s*(\")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.o2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.o2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.o2</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.o2</string>
						</dict>
					</dict>
					<key>name</key>
					<string>tag.doublequotes.o2</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>storage.type.label.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^([*])([\w-_]+)</string>
							<key>name</key>
							<string>label.tag.o2</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.o2</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([\w &amp;&gt;&lt;;?\.,\'_\-*=\(\)]+)</string>
							<key>name</key>
							<string>tag.properties.o2</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.o2</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.tag.o2</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.o2</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([\w]+)\s*(=)\s*([\w&amp;:\(\)\.,0-9-_a-zA-Z\p{Han}\p{Hiragana}\p{Katakana}]{0,}+)</string>
					<key>name</key>
					<string>tag.noquotes.o2</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.o2</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;|//)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.o2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.o2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.o2</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.label.o2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.label.o2</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.tag.o2</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([*])([\w-_]+)\s*|\s*([\w-_ ]+?)</string>
			<key>name</key>
			<string>label.o2</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-tag.o2</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\[\[</string>
			<key>name</key>
			<string>invalid.o2</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-tag.o2</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\]\]</string>
			<key>name</key>
			<string>invalid.o2</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bad-at.o2</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\@\n</string>
			<key>name</key>
			<string>invalid.o2</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.o2</string>
	<key>uuid</key>
	<string>1cac63ad-a992-4063-9ac0-1bbcf7b12924</string>
</dict>
</plist>
